export const mockTrips = [
  {
    id: '1',
    driver: 'Karim B.',
    initials: 'KB',
    avatarColor: '#2C3E6B',
    rating: 4.9,
    departureTime: '8h15',
    minutesUntil: 8,
    seats: 2,
    price: 6,
    isAIRecommended: true,
    destination: 'Université',
  },
  {
    id: '2',
    driver: 'Fatima Z.',
    initials: 'FZ',
    avatarColor: '#C8553D',
    rating: 4.7,
    departureTime: '8h30',
    minutesUntil: 23,
    seats: 3,
    price: 10,
    isAIRecommended: false,
    destination: 'Université',
  },
  {
    id: '3',
    driver: 'Hassan M.',
    initials: 'HM',
    avatarColor: '#7A9E7E',
    rating: 4.8,
    departureTime: '8h45',
    minutesUntil: 38,
    seats: 1,
    price: 7,
    isAIRecommended: false,
    destination: 'Université',
  },
  {
    id: '4',
    driver: 'Aicha R.',
    initials: 'AR',
    avatarColor: '#D4933A',
    rating: 4.5,
    departureTime: '9h00',
    minutesUntil: 53,
    seats: 4,
    price: 13,
    isAIRecommended: false,
    destination: 'Université',
  },
];
